export const INITIAL_CATEGORIES = [
  {
    id: "vegetables-fruits",
    name: "Vegetables & Fruits",
    teluguName: "కూరగాయలు & పండ్లు",
    icon: "Apple",
    image: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=400&auto=format&fit=crop&q=80",
    accentColor: "#10b981",
    subcategories: ["Fresh Vegetables", "Fresh Fruits", "Organic Exotic", "Leafy Greens", "Season's Best"],
    itemCount: 18,
    isPopular: true,
  },
  {
    id: "dairy-bread-eggs",
    name: "Dairy, Bread & Eggs",
    teluguName: "పాలు, బ్రెడ్ & గుడ్లు",
    icon: "Milk",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80",
    accentColor: "#3b82f6",
    subcategories: ["Milk & Cream", "Artisanal Bread", "Farm Eggs", "Butter & Cheese", "Curd & Paneer"],
    itemCount: 14,
    isPopular: true,
  },
  {
    id: "snacks-munchies",
    name: "Snacks & Munchies",
    teluguName: "స్నాక్స్ & తినుబండారాలు",
    icon: "Cookie",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop&q=80",
    accentColor: "#f59e0b",
    subcategories: ["Chips & Crisps", "Roasted Nuts", "Chocolates", "Namkeen & Savories", "Energy Bars"],
    itemCount: 12,
    isPopular: true,
  },
  {
    id: "beverages",
    name: "Cold Drinks & Juices",
    teluguName: "శీతల పానీయాలు & జ్యూస్‌లు",
    icon: "CupSoda",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&auto=format&fit=crop&q=80",
    accentColor: "#ef4444",
    subcategories: ["Cold Pressed Juices", "Kombucha & Tonics", "Soft Drinks", "Coconut Water", "Energy Drinks"],
    itemCount: 10,
    isPopular: false,
  },
  {
    id: "organic-staples",
    name: "Atta, Rice & Dal",
    teluguName: "పిండి, బియ్యం & పప్పులు",
    icon: "Wheat",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80",
    accentColor: "#8b5cf6",
    subcategories: ["Organic Dals & Pulses", "Basmati & Brown Rice", "Whole Wheat Atta", "Cold Pressed Oils", "Spices & Herbs"],
    itemCount: 16,
    isPopular: true,
  },
  {
    id: "instant-frozen",
    name: "Instant & Frozen Foods",
    teluguName: "ఇన్‌స్టంట్ & ఫ్రోజెన్ ఆహారాలు",
    icon: "Pizza",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80",
    accentColor: "#ec4899",
    subcategories: ["Noodles & Pasta", "Frozen Veggies & Fries", "Ready-to-Eat Curries", "Ice Creams"],
    itemCount: 8,
    isPopular: false,
  },
  {
    id: "personal-care",
    name: "Personal & Baby Care",
    teluguName: "వ్యక్తిగత & బేబీ కేర్",
    icon: "Sparkles",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&auto=format&fit=crop&q=80",
    accentColor: "#06b6d4",
    subcategories: ["Skincare Essentials", "Bath & Body", "Baby Care Wipes", "Oral Hygiene"],
    itemCount: 9,
    isPopular: false,
  },
  {
    id: "kitchen-household",
    name: "Home & Cleaning",
    teluguName: "గృహ & శుభ్రపరిచే వస్తువులు",
    icon: "Home",
    image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=80",
    accentColor: "#14b8a6",
    subcategories: ["Eco Dishwash", "Laundry Detergents", "Surface Sprays", "Garbage Bags"],
    itemCount: 8,
    isPopular: false,
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: "prod-tomato-hybrid",
    name: "Hybrid Fresh Tomatoes",
    teluguName: "తాజా టమోటాలు (హైబ్రిడ్)",
    category: "vegetables-fruits",
    subcategory: "Fresh Vegetables",
    price: 32,
    originalPrice: 48,
    discountPercentage: 33,
    unit: "500 g",
    inStock: true,
    stockCount: 84,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80",
    ],
    badge: "⚡ 10-Min Flash Deal",
    rating: 4.8,
    reviewsCount: 342,
    reviews: [
      {
        id: "rev-tom-1",
        productId: "prod-tomato-hybrid",
        userName: "Ananya Rao",
        rating: 5,
        title: "Super fresh and firm!",
        comment: "Ordered these for morning rasam and salads. Received within 9 minutes, perfectly red and not a single damaged tomato.",
        verifiedPurchase: true,
        createdAt: "2026-08-20T14:22:00Z",
        helpfulCount: 14,
        tags: ["Farm Fresh", "10-Min Fast Delivery", "Juicy"],
      },
      {
        id: "rev-tom-2",
        productId: "prod-tomato-hybrid",
        userName: "Karthik Sundaram",
        rating: 5,
        title: "Much better than local supermarket",
        comment: "Hydroponic quality is clearly noticeable. Firm texture and great shelf life. Kept in fridge for 5 days without getting soft.",
        verifiedPurchase: true,
        createdAt: "2026-08-18T09:15:00Z",
        helpfulCount: 8,
        tags: ["High Quality", "Great Value"],
      },
      {
        id: "rev-tom-3",
        productId: "prod-tomato-hybrid",
        userName: "Sneha Patil",
        rating: 4,
        title: "Good ripeness",
        comment: "Fresh and clean packaging with temperature controlled bag. Very satisfied with the quick dispatch.",
        verifiedPurchase: true,
        createdAt: "2026-08-15T18:40:00Z",
        helpfulCount: 3,
        tags: ["Eco Packaging"],
      },
    ],
    description: "Handpicked firm and juicy red hybrid tomatoes directly sourced from local Karnataka hydroponic greenhouses at 4 AM every morning.",
    nutritionalInfo: { calories: "18 kcal / 100g", protein: "0.9g", carbs: "3.9g", fat: "0.2g" },
    origin: "Hosur Hydroponics Co-Op",
    isOrganic: true,
    shelfLife: "4 Days in cool storage",
    deliveryTimeMinutes: 8,
    tags: ["bestseller", "organic", "vegetables", "daily-essentials"],
  },
  {
    id: "prod-avocado-hass",
    name: "Imported Hass Avocado (Ripe & Ready)",
    teluguName: "అవోకాడో (హాస్)",
    category: "vegetables-fruits",
    subcategory: "Organic Exotic",
    price: 149,
    originalPrice: 199,
    discountPercentage: 25,
    unit: "2 pcs (approx 320g)",
    inStock: true,
    stockCount: 28,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&auto=format&fit=crop&q=80",
    badge: "🥑 Exotic Pick",
    rating: 4.9,
    reviewsCount: 189,
    reviews: [
      {
        id: "rev-avo-1",
        productId: "prod-avocado-hass",
        userName: "Vikram Malhotra",
        rating: 5,
        title: "Perfect buttery ripeness!",
        comment: "Hard to find good Hass avocados in Indiranagar. These were buttery smooth, ready to eat without any black spots inside. Superb for avocado sourdough toast.",
        verifiedPurchase: true,
        createdAt: "2026-08-19T11:00:00Z",
        helpfulCount: 19,
        tags: ["Perfect Ripeness", "Keto Bowl", "Super Buttery"],
      },
      {
        id: "rev-avo-2",
        productId: "prod-avocado-hass",
        userName: "Meera Krishnan",
        rating: 5,
        title: "Guacamole perfection",
        comment: "Made fresh guacamole for family evening snack. Texture was creamy and taste was genuine imported Hass quality.",
        verifiedPurchase: true,
        createdAt: "2026-08-17T16:30:00Z",
        helpfulCount: 7,
        tags: ["Guacamole", "Fresh Quality"],
      },
    ],
    description: "Buttery, rich Hass avocados perfect for morning toast, guacamole, and keto bowls. Tested for ideal firmness before packaging.",
    nutritionalInfo: { calories: "160 kcal / 100g", protein: "2g", carbs: "8.5g", fat: "14.7g" },
    origin: "Organic Valley Farms",
    isOrganic: true,
    shelfLife: "2-3 Days",
    deliveryTimeMinutes: 10,
    tags: ["exotic", "keto", "superfood", "imported"],
  },
  {
    id: "prod-shimla-apples",
    name: "Crisp Shimla Royal Apples",
    teluguName: "షిమ్లా రాయల్ యాపిల్స్ (తాజా)",
    category: "vegetables-fruits",
    subcategory: "Fresh Fruits",
    price: 135,
    originalPrice: 170,
    discountPercentage: 20,
    unit: "4 pcs (approx 600g)",
    inStock: true,
    stockCount: 65,
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80",
    badge: "🍎 Sweet & Juicy",
    rating: 4.7,
    reviewsCount: 512,
    description: "Naturally orchard-ripened Shimla Royal Delicious apples. Sweet, crisp crunch with rich natural aroma without synthetic wax coat.",
    nutritionalInfo: { calories: "52 kcal / 100g", protein: "0.3g", carbs: "14g", fat: "0.2g" },
    origin: "Himachal Highlands",
    isOrganic: true,
    shelfLife: "7 Days refrigerated",
    deliveryTimeMinutes: 10,
    tags: ["fruits", "seasonal", "kids-favorite"],
  },
  {
    id: "prod-coriander-mint-pack",
    name: "Fresh Coriander & Mint Combo",
    teluguName: "కొత్తిమీర & పుదీనా కాంబో",
    category: "vegetables-fruits",
    subcategory: "Leafy Greens",
    price: 18,
    originalPrice: 30,
    discountPercentage: 40,
    unit: "1 Bunch each (200g)",
    inStock: true,
    stockCount: 95,
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&auto=format&fit=crop&q=80",
    badge: "🌿 Clean & Hydro-washed",
    rating: 4.8,
    reviewsCount: 420,
    description: "Triple ozonated washed farm fresh coriander and aromatic spearmint bunch. Ready to chop for chutneys, garnishing and detox teas.",
    nutritionalInfo: { calories: "23 kcal / 100g", protein: "2.1g", carbs: "3.7g", fat: "0.5g" },
    origin: "Kengeri Green Belts",
    isOrganic: true,
    shelfLife: "3 Days in zip-lock",
    deliveryTimeMinutes: 8,
    tags: ["daily-essentials", "herbs", "fresh"],
  },
  {
    id: "prod-amul-gold-milk",
    name: "Amul Gold Full Cream Fresh Milk",
    teluguName: "అమూల్ గోల్డ్ పాలు (ఫుల్ క్రీమ్)",
    category: "dairy-bread-eggs",
    subcategory: "Milk & Cream",
    price: 34,
    originalPrice: 34,
    discountPercentage: 0,
    unit: "500 ml Pouch",
    inStock: true,
    stockCount: 140,
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
    badge: "🥛 100% Chilled Delivered",
    rating: 4.9,
    reviewsCount: 1240,
    reviews: [
      {
        id: "rev-mlk-1",
        productId: "prod-amul-gold-milk",
        userName: "Suresh Nambiar",
        rating: 5,
        title: "Cold chain is real! Arrived chilled in 7 mins",
        comment: "Always worried about milk packets getting warm in delivery. Leafbasket arrived ice-cold in their insulated cool box. Excellent morning service.",
        verifiedPurchase: true,
        createdAt: "2026-08-21T06:45:00Z",
        helpfulCount: 22,
        tags: ["Ice Cold", "Early Morning", "Fast 7 Mins"],
      },
    ],
    description: "Pasteurised homogenized fresh full cream milk with 6.0% fat and 9.0% SNF. Kept below 4°C in insulated cooling pods during bike dispatch.",
    nutritionalInfo: { calories: "87 kcal / 100ml", protein: "3.2g", carbs: "5.0g", fat: "6.0g" },
    origin: "Amul Dairy Gujarat/Bengaluru",
    isOrganic: false,
    shelfLife: "2 Days refrigerated",
    deliveryTimeMinutes: 7,
    tags: ["bestseller", "dairy", "breakfast", "chilled"],
  },
  {
    id: "prod-sourdough-bread",
    name: "Artisan Country Sourdough Loaf",
    teluguName: "ఆర్టిసన్ సోర్డో బ్రెడ్",
    category: "dairy-bread-eggs",
    subcategory: "Artisanal Bread",
    price: 110,
    originalPrice: 145,
    discountPercentage: 24,
    unit: "400 g",
    inStock: true,
    stockCount: 19,
    image: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=80",
    badge: "🥖 Baked Today 6 AM",
    rating: 4.9,
    reviewsCount: 230,
    description: "36-hour slow fermented wild yeast sourdough with open crumb and golden caramelized crust. Zero preservatives, zero palm oil.",
    nutritionalInfo: { calories: "210 kcal / 100g", protein: "8.5g", carbs: "42g", fat: "1.2g" },
    origin: "The Crust Craft Bakery",
    isOrganic: true,
    shelfLife: "3 Days",
    deliveryTimeMinutes: 9,
    tags: ["artisanal", "bakery", "breakfast", "vegan"],
  },
  {
    id: "prod-organic-eggs-6",
    name: "Free-Range Brown Farm Eggs",
    teluguName: "నాటుకోడి గోధుమ రంగు గుడ్లు (6 గుడ్లు)",
    category: "dairy-bread-eggs",
    subcategory: "Farm Eggs",
    price: 79,
    originalPrice: 95,
    discountPercentage: 17,
    unit: "Pack of 6 pcs",
    inStock: true,
    stockCount: 52,
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&auto=format&fit=crop&q=80",
    badge: "🍳 High Protein 6g/egg",
    rating: 4.8,
    reviewsCount: 680,
    description: "Antibiotic-free pasture raised vegetarian grain-fed hen eggs. Thick yolk with bright golden color and clean shatterproof paper pulp box.",
    nutritionalInfo: { calories: "72 kcal / egg", protein: "6.3g", carbs: "0.4g", fat: "4.8g" },
    origin: "Nandi Valley Free Range Poultry",
    isOrganic: true,
    shelfLife: "14 Days",
    deliveryTimeMinutes: 8,
    tags: ["protein", "eggs", "breakfast", "organic"],
  },
  {
    id: "prod-greek-yogurt-berries",
    name: "Epigamia Greek Yogurt - Wild Blueberry",
    teluguName: "ఎపిగామియా గ్రీక్ పెరుగు (బ్లూబెర్రీ)",
    category: "dairy-bread-eggs",
    subcategory: "Curd & Paneer",
    price: 55,
    originalPrice: 65,
    discountPercentage: 15,
    unit: "90 g Cup",
    inStock: true,
    stockCount: 38,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80",
    badge: "🫐 6g Real Protein",
    rating: 4.8,
    reviewsCount: 310,
    description: "High-protein Greek yogurt blended with real chunky wild blueberry compote. Low sugar, active gut-friendly probiotic cultures.",
    nutritionalInfo: { calories: "95 kcal / cup", protein: "6.0g", carbs: "12g", fat: "2.1g" },
    origin: "Epigamia Foods",
    isOrganic: false,
    shelfLife: "10 Days refrigerated",
    deliveryTimeMinutes: 10,
    tags: ["healthy", "snacks", "dessert", "protein"],
  },
  {
    id: "prod-roasted-california-almonds",
    name: "Slow-Roasted California Jumbo Almonds",
    teluguName: "వేయించిన కాలిఫోర్నియా బాదం",
    category: "snacks-munchies",
    subcategory: "Roasted Nuts",
    price: 240,
    originalPrice: 320,
    discountPercentage: 25,
    unit: "250 g Pouch",
    inStock: true,
    stockCount: 45,
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=500&auto=format&fit=crop&q=80",
    badge: "✨ Light Himalayan Salt",
    rating: 4.9,
    reviewsCount: 410,
    description: "Crunchy oven-roasted non-pareil almonds dusted with pink Himalayan rock salt. Rich in Vitamin E, magnesium, and dietary fiber.",
    nutritionalInfo: { calories: "579 kcal / 100g", protein: "21.1g", carbs: "21.6g", fat: "49.9g" },
    origin: "NutriDelight Imports",
    isOrganic: true,
    shelfLife: "6 Months",
    deliveryTimeMinutes: 10,
    tags: ["nuts", "snacks", "healthy", "premium"],
  },
  {
    id: "prod-dark-chocolate-70",
    name: "Single Origin 70% Dark Chocolate Bar",
    teluguName: "డార్క్ చాక్లెట్ (70%)",
    category: "snacks-munchies",
    subcategory: "Chocolates",
    price: 175,
    originalPrice: 220,
    discountPercentage: 20,
    unit: "80 g Bar",
    inStock: true,
    stockCount: 33,
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80",
    badge: "🍫 Bean-to-Bar Idukki",
    rating: 4.9,
    reviewsCount: 164,
    description: "Craft artisanal bean-to-bar dark chocolate with cocoa beans grown in the Western Ghats of Idukki. Velvety, with notes of berries and caramel.",
    nutritionalInfo: { calories: "550 kcal / 100g", protein: "7.8g", carbs: "35g", fat: "42g" },
    origin: "Western Ghats Cocoa Collective",
    isOrganic: true,
    shelfLife: "9 Months",
    deliveryTimeMinutes: 10,
    tags: ["chocolate", "treats", "organic", "vegan"],
  },
  {
    id: "prod-cold-pressed-orange-juice",
    name: "Cold Pressed Valencia Orange Juice",
    teluguName: "తాజా నారింజ రసం (కోల్డ్ ప్రెస్డ్)",
    category: "beverages",
    subcategory: "Cold Pressed Juices",
    price: 99,
    originalPrice: 130,
    discountPercentage: 24,
    unit: "300 ml Bottle",
    inStock: true,
    stockCount: 22,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80",
    badge: "🍊 100% Pure Juice (No Sugar)",
    rating: 4.9,
    reviewsCount: 290,
    description: "Never heated, hydraulic cold-pressed pure Valencia orange juice with subtle pulp. Rich in natural bio-available Vitamin C.",
    nutritionalInfo: { calories: "45 kcal / 100ml", protein: "0.7g", carbs: "10.4g", fat: "0.2g" },
    origin: "Raw Pressery Co.",
    isOrganic: true,
    shelfLife: "4 Days (chilled)",
    deliveryTimeMinutes: 9,
    tags: ["beverages", "immunity", "pure-juice", "breakfast"],
  },
  {
    id: "prod-tender-coconut-water",
    name: "Fresh Pollachi Tender Coconut Water",
    teluguName: "పొల్లాచ్చి లేత కొబ్బరి నీళ్ళు",
    category: "beverages",
    subcategory: "Coconut Water",
    price: 65,
    originalPrice: 75,
    discountPercentage: 13,
    unit: "1 Pc (approx 350ml)",
    inStock: true,
    stockCount: 78,
    image: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=500&auto=format&fit=crop&q=80",
    badge: "🥥 Shaved & Easy to Open",
    rating: 4.9,
    reviewsCount: 880,
    description: "Naturally electrolyte rich, sweet tender coconut directly from Pollachi groves. Diamond-cut pre-drilled with eco bamboo straw provided.",
    nutritionalInfo: { calories: "19 kcal / 100ml", protein: "0.7g", carbs: "3.7g", fat: "0.2g" },
    origin: "Pollachi Groves",
    isOrganic: true,
    shelfLife: "2 Days",
    deliveryTimeMinutes: 8,
    tags: ["hydrating", "beverages", "organic", "natural"],
  },
  {
    id: "prod-daawat-basmati-rice",
    name: "Daawat Rozana Super Basmati Rice",
    teluguName: "దావత్ సూపర్ బాస్మతి బియ్యం",
    category: "organic-staples",
    subcategory: "Basmati & Brown Rice",
    price: 189,
    originalPrice: 245,
    discountPercentage: 23,
    unit: "1 kg Pack",
    inStock: true,
    stockCount: 60,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    badge: "🍚 2-Year Aged Grains",
    rating: 4.8,
    reviewsCount: 540,
    description: "Fluffy, long grain aromatic basmati rice aged to perfection. Grains stay separate and double in length when cooked for biryanis and pulao.",
    nutritionalInfo: { calories: "356 kcal / 100g", protein: "8.5g", carbs: "78g", fat: "0.6g" },
    origin: "Punjab Tarai Plains",
    isOrganic: false,
    shelfLife: "12 Months",
    deliveryTimeMinutes: 10,
    tags: ["staples", "rice", "bestseller", "dinner"],
  },
  {
    id: "prod-organic-tur-dal",
    name: "Organic Unpolished Tur Dal (Arhar)",
    teluguName: "ఆర్గానిక్ కందిపప్పు (అన్‌పాలిష్డ్)",
    category: "organic-staples",
    subcategory: "Organic Dals & Pulses",
    price: 165,
    originalPrice: 210,
    discountPercentage: 21,
    unit: "1 kg Pack",
    inStock: true,
    stockCount: 48,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80",
    badge: "🌱 Zero Chemical Polish",
    rating: 4.9,
    reviewsCount: 390,
    description: "Certified chemical-free unpolished yellow split pigeon peas (arhar dal). Naturally retains protein, high dietary fiber and rich earthy taste.",
    nutritionalInfo: { calories: "343 kcal / 100g", protein: "22g", carbs: "62g", fat: "1.5g" },
    origin: "Vidarbha Organic Farmers",
    isOrganic: true,
    shelfLife: "9 Months",
    deliveryTimeMinutes: 10,
    tags: ["staples", "organic", "high-protein", "dal"],
  },
];

export const INITIAL_COUPONS = [
  {
    code: "LEAF100",
    description: "Flat ₹100 OFF on your first 3 orders above ₹399",
    discountPercentage: 25,
    maxDiscount: 100,
    minOrderAmount: 399,
    validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    usageCount: 142,
    isActive: true,
  },
  {
    code: "FRESH50",
    description: "Flat ₹50 OFF on all fresh fruits & veggies above ₹199",
    discountPercentage: 20,
    maxDiscount: 50,
    minOrderAmount: 199,
    validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    usageCount: 380,
    isActive: true,
  },
  {
    code: "SUPERFAST",
    description: "10-Minute lightning delivery free + ₹30 instant discount",
    discountPercentage: 15,
    maxDiscount: 30,
    minOrderAmount: 149,
    validUntil: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    usageCount: 890,
    isActive: true,
  },
];

export const INITIAL_RIDERS = [
  {
    riderId: "rider-rajesh-01",
    name: "Rajesh K.",
    phone: "+91 98452 38471",
    vehicleType: "Electric Ather 450X",
    vehicleNumber: "KA 01 EJ 7892",
    rating: 4.95,
    completedDeliveries: 1480,
    currentStatus: "en_route",
    currentLocation: {
      lat: 12.9724,
      lng: 77.6385,
      heading: 110,
      speedKmH: 26,
      lastUpdated: new Date(),
    },
    batteryPercentage: 88,
  },
  {
    riderId: "rider-anand-02",
    name: "Anand M.",
    phone: "+91 97401 84920",
    vehicleType: "Ola S1 Pro",
    vehicleNumber: "KA 05 MN 2210",
    rating: 4.88,
    completedDeliveries: 940,
    currentStatus: "idle",
    currentLocation: {
      lat: 12.9782,
      lng: 77.6408,
      heading: 45,
      speedKmH: 0,
      lastUpdated: new Date(),
    },
    batteryPercentage: 94,
  },
  {
    riderId: "rider-kiran-03",
    name: "Kiran Dev",
    phone: "+91 99008 17263",
    vehicleType: "TVS iQube",
    vehicleNumber: "KA 03 HL 9012",
    rating: 4.92,
    completedDeliveries: 1120,
    currentStatus: "idle",
    currentLocation: {
      lat: 12.9698,
      lng: 77.6331,
      heading: 270,
      speedKmH: 0,
      lastUpdated: new Date(),
    },
    batteryPercentage: 76,
  },
];

export const INITIAL_SAMPLE_ORDERS = [
  {
    orderId: "LB-88492",
    customerName: "Priya Sharma",
    customerPhone: "+91 98450 12345",
    deliveryAddress: {
      street: "Flat 402, Oakwood Residency, 12th Main",
      flat: "402",
      landmark: "Near BDA Complex",
      area: "Indiranagar",
      city: "Bengaluru",
      pincode: "560038",
      lat: 12.9716,
      lng: 77.6412,
    },
    items: [
      {
        productId: "prod-tomato-hybrid",
        name: "Hybrid Fresh Tomatoes",
        price: 32,
        quantity: 2,
        unit: "500 g",
        image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
      },
      {
        productId: "prod-amul-gold-milk",
        name: "Amul Gold Full Cream Fresh Milk",
        price: 34,
        quantity: 2,
        unit: "500 ml Pouch",
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
      },
      {
        productId: "prod-coriander-mint-pack",
        name: "Fresh Coriander & Mint Combo",
        price: 18,
        quantity: 1,
        unit: "1 Bunch each (200g)",
        image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&auto=format&fit=crop&q=80",
      },
    ],
    itemTotal: 150,
    deliveryFee: 0,
    packagingFee: 5,
    tipAmount: 20,
    couponDiscount: 30,
    couponCode: "SUPERFAST",
    totalAmount: 145,
    paymentMethod: "upi" as const,
    paymentStatus: "paid" as const,
    orderStatus: "out_for_delivery" as const,
    statusTimeline: [
      { status: "placed", timestamp: new Date(Date.now() - 6 * 60 * 1000), note: "Order placed & verified" },
      { status: "packed", timestamp: new Date(Date.now() - 4 * 60 * 1000), note: "Packed in pod #14 with cooling gel" },
      { status: "out_for_delivery", timestamp: new Date(Date.now() - 2 * 60 * 1000), note: "Rider Rajesh K. picked up order" },
    ],
    riderDetails: {
      riderId: "rider-rajesh-01",
      name: "Rajesh K.",
      phone: "+91 98452 38471",
      vehicleNumber: "KA 01 EJ 7892",
      rating: 4.95,
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      lat: 12.9724,
      lng: 77.6385,
    },
    etaMinutes: 4,
    otp: "4829",
    notes: "Please do not ring bell if baby is sleeping.",
    createdAt: new Date(Date.now() - 6 * 60 * 1000),
    updatedAt: new Date(),
  },
];
